"""Modify models.task.py

Revision ID: 5805e46688db
Revises: 0154d35eabbe
Create Date: 2025-01-27 01:46:57.726018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5805e46688db'
down_revision: Union[str, None] = '0154d35eabbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tasks', ['user_id'], ['id'])
    # ### end Alembic commands ###
